Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Max: 192

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 20

Style/SignalException:
  EnforcedStyle: only_raise
